#
# Copyright (C) 2018 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-$(CONFIG_INIT_CD) += cd.o
obj-$(CONFIG_INIT_LS) += ls.o
obj-$(CONFIG_INIT_ECHO) += echo.o
obj-$(CONFIG_INIT_CAT) += cat.o
obj-$(CONFIG_INIT_MKDIR) += mkdir.o
obj-$(CONFIG_INIT_RM) += rm.o
obj-$(CONFIG_INIT_PINSAMPLER) += pinsampler.o
obj-$(CONFIG_INIT_PWMCTRL) += pwmctrl.o
obj-$(CONFIG_INIT_I2CCFG) += i2ccfg.o
obj-$(CONFIG_INIT_TEST) += test.o test/
