#
# Copyright (C) 2019 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-y := esp8266.o


cppflags-$(CONFIG_ESP8266_DEBUG) := -DBUILD_KERNEL_LOG_DEBUG
