#
# Copyright (C) 2020 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-y := start.o init.o core.o interrupt.o thread.o memory.o syscall.o timer.o sched.o rootfs.o
