#
# Copyright (C) 2023 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



# kernel
obj-y := \
	init.o \
	kernel/

# libbrick
obj-nobuiltin-y := libbrick.o

libbrick-y := \
	init.o \
	lib/
