#
# Copyright (C) 2018 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



hostbin-y := gen_lds_plugin

gen_lds_plugin-y := plugin.o sys/


hostcppflags-y := -I"include/"
hostcflags-y := \
	-Wno-unused-function \
	-fno-builtin
