#ifndef AVR_INTERRUPT_H
#define AVR_INTERRUPT_H


/* macros */
#define NINTERRUPTS			35


/* types */
typedef enum int_num_t{
	INT_NONE = 0,
	INT_0,
	INT_1,
	INT_2,
	INT_PCINT0,
	INT_PCINT1,
	INT_PCINT2,
	INT_PCINT3,
	INT_WATCHDOG,
	INT_TIMER2_COMPA,
	INT_TIMER2_COMPB,
	INT_TIMER2_OVFL,
	INT_TIMER1_CAMPTURE,
	INT_TIMER1_COMPA,
	INT_TIMER1_COMPB,
	INT_TIMER1_OVFL,
	INT_TIMER0_COMPA,
	INT_TIMER0_COMPB,
	INT_TIMER0_OVFL,
	INT_SPI_TX,
	INT_USART0_RX,
	INT_USART0_UDRE,
	INT_USART0_TX,
	INT_ACOMP,
	INT_ADC,
	INT_EEPROM_RDY,
	INT_TWI,
	INT_SPM_RDY,
	INT_USART1_RX,
	INT_USART1_UDRE,
	INT_USART1_TX,
	INT_TIMER3_CAMPTURE,
	INT_TIMER3_COMPA,
	INT_TIMER3_COMPB,
	INT_TIMER3_OVFL,
	INT_ALL,
} int_num_t;


#endif // AVR_INTERRUPT_H
