#
# Copyright (C) 2018 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-$(CONFIG_SC_FILESYSTEM) += file.o
obj-$(CONFIG_SC_TIME) += sleep.o
obj-$(CONFIG_SC_SCHED) += process.o thread.o
