#
# Copyright (C) 2019 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



hostbin-y := gen_lds_memory


gen_lds_memory-y := memory.o

hostcppflags-y := -I"include/"
hostcflags-y := -Wno-unused-function
