#
# Copyright (C) 2024 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-y := \
	core.o \
	intctrl.o \
	inthdlr.o \
	isr.o \
	nvic.o \
	start.o \
	syscall.o \
	systick.o \
	thread.o
