#
# Copyright (C) 2019 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-$(CONFIG_AVR_PWM_8BIT) += avr_8bit.o
obj-$(CONFIG_AVR_PWM_16BIT) += avr_16bit.o


cppflags-$(CONFIG_PWM_DEBUG) := -DBUILD_KERNEL_MSG_DEBUG
