#
# Copyright (C) 2018 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-y := shell.o readline.o cmd.o cmds/

obj-$(CONFIG_INIT_HISTORY) += history.o
