#
# Copyright (C) 2022 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-y := vram.o

obj-$(CONFIG_VRAM_RAW) += raw.o
obj-$(CONFIG_VRAM_TERM) += term.o
