#
# Copyright (C) 2016 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-y := inet.o netdev.o socket.o


cppflags-$(CONFIG_SC_SOCKET_DEBUG) := -DBUILD_KERNEL_MSG_DEBUG
