#
# Copyright (C) 2018 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-y += close_sync.o
obj-y += thread.o
obj-y += tty.o
obj-y += stat.o
obj-y += signal.o
obj-y += kill.o
obj-y += exit.o
obj-y += gpioint.o
