#
# Copyright (C) 2016 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-y := init.o unistd/ stdlib/ stdio/

obj-$(CONFIG_SC_TIME) += time.o
obj-$(CONFIG_SC_SCHED) += sched.o
obj-$(CONFIG_SC_SIGNAL) += signal.o
