#
# Copyright (C) 2017 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-y := loop.o


cppflags-$(CONFIG_LOOP_DEBUG) := -DBUILD_KERNEL_MSG_DEBUG
