#
# Copyright (C) 2017 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-$(CONFIG_LOOP_BLOCK) += block.o
obj-$(CONFIG_LOOP_TERM) += term.o
obj-$(CONFIG_LOOP_VRAM) += vram.o


cppflags-$(CONFIG_LOOP_DEBUG) := -DBUILD_KERNEL_LOG_DEBUG
