#
# Copyright (C) 2020 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



hostobj-y := state.o ops.o interrupt.o timer.o uart.o display.o sys.o


sys-y := $(build_tree)/sys/vram.o
