#
# Copyright (C) 2018 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-$(CONFIG_LIB_STREAM) += stream.o
obj-$(CONFIG_LIB_PRINTF) += file.o
