#
# Copyright (C) 2021 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-y := memory.o

obj-$(DEVTREE_ARCH_MULTI_CORE) += ipi.o


cppflags-y := -DTEST_TYPE=\"kernel\"
