#
# Copyright (C) 2019 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-y := itf.o
obj-$(CONFIG_I2C_AVR_INTERRUPT) += int.o
obj-$(CONFIG_I2C_AVR_POLLING) += poll.o
