#
# Copyright (C) 2022 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#


obj-y := readline.o line.o

obj-$(CONFIG_READLINE_HISTORY) += history.o
