#
# Copyright (C) 2016 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



hostbin-y := memlayout memlayout_check

memlayout-y := main.o
memlayout_check-y := check.o

hostcppflags-y := -I"include/"
hostcflags-y := -fno-builtin
