#
# Copyright (C) 2016 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



hostbin-y := memlayout

memlayout-y := main.o sys/

hostcppflags-y := -I"include/"
hostcflags-y := -fno-builtin
