obj-$(CONFIG_INIT_CD) += cd.o
obj-$(CONFIG_INIT_LS) += ls.o
obj-$(CONFIG_INIT_ECHO) += echo.o
obj-$(CONFIG_INIT_CAT) += cat.o
obj-$(CONFIG_INIT_MKDIR) += mkdir.o
obj-$(CONFIG_INIT_RM) += rm.o
obj-$(CONFIG_INIT_TEST) += test.o
