#
# Copyright (C) 2016 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-$(CONFIG_DRIVER_LOOPBACK) += loop/
obj-$(CONFIG_DRIVER_TERM) += term/
obj-$(CONFIG_DRIVER_UART) += uart/
obj-$(CONFIG_DRIVER_GPIO) += gpio/
obj-$(CONFIG_DRIVER_PWM) += pwm/
obj-$(CONFIG_DRIVER_SPI) += spi/
obj-$(CONFIG_DRIVER_EEPROM) += eeprom/
obj-$(CONFIG_DRIVER_I2C) += i2c/
obj-$(CONFIG_DRIVER_ESP8266) += esp8266/
