#
# Copyright (C) 2023 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



subdir-y := \
	arch/ \
	devtree/ \
	fontc/ \
	linker/ \
	memlayout/
