#
# Copyright (C) 2018 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



hostbin-y := avrconfig


avrconfig-y := main.o watchdog.o

hostcppflags-y += -I"include/"
