#
# Copyright (C) 2019 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-$(CONFIG_ATMEL_PMC) += pmc.o
obj-$(CONFIG_ATMEL_EEFC) += eefc.o
obj-$(CONFIG_ATMEL_PIO) += pio.o

pmc-cflags := -O0
