#
# Copyright (C) 2016 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-y := string.o stream.o list.o list1.o queue.o stack.o memblock.o vector.o inet.o devtree.o ringbuf.o patmat.o
hostobj-y := $(obj-y)


cppflags-y := -DTEST_TYPE=\"unit\"
hostcppflags-y := $(cppflags-y)
