#
# Copyright (C) 2024 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



obj-y := \
	bootloader.o \
	clocks.o \
	core.o \
	iomux.o \
	resets.o \
	soc.o

obj-$(DEVTREE_ARCH_MULTI_CORE) += multi-core.o
